services:
  frontend:
    image: tanmoydas02/efootball25-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"

  backend:
    image: tanmoydas02/efootball25-backend:latest
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: efootball

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: efootball
