pipeline {
    agent any

    stages {
        stage ('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage ('Workspace check') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
    }
}