pipeline {
    agent any

    stages {
        stage ('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage ('Workspace check') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage ('Docker check') {
            steps {
                sh 'docker --version'
            }
        }

        stage ('Build backend image') {
            steps {
                sh 'docker build -t efootball25-backend:latest ./app/efootball25/backend'
            }
        }

        stage ('Build frontend image') {
            steps {
                sh 'docker build -t efootball25-frontend:latest ./app/efootball25/frontend'
            }
        }
    }
}